### ISSUE TITLE
 image is not showed in new TLS1.2 protocol HTTPS

### ISSUE THREAD

**Issue by batorshih** [smhdk/KM-Popup-Image-Slider#3]

**Comment by smhdk** [comment]
Hi @batorshih ,

Can you write device android api number and image url you tried?

**Comment by batorshih** [comment]
hi @smhdk 
api version is less than 21, and image url is https://zgm.mn/media/zgm/content/12_SAR/zgm_hevtee_rmpWBUP.jpg

**Comment by batorshih** [comment]
sdkversion is less than 18
