### ISSUE TITLE
Show selected image

### ISSUE THREAD

**Issue by AlexandruDev** [smhdk/KM-Popup-Image-Slider#5]
Let's say that I have a list with 10 images. When I press the fourth image the Popup-Image-Slider starts but with the first image and not with the selected one.

```
private fun showFullscreenImage(images: MutableList<String>): Dialog {
        return PopopDialogBuilder(context)
                .setList(images)
                .setHeaderBackgroundColor(R.color.textColorPrimary)
                .setDialogBackgroundColor(R.color.color_dialog_bg)
                .setCloseDrawable(R.drawable.ic_close_white_24dp)
                .setLoadingView(R.layout.loading_view)
                .setDialogStyle(R.style.DialogStyle)
                .showThumbSlider(false)
                .setIsZoomable(true)
                .setSelectorIndicator(R.drawable.sample_indicator_selector)
                .build()
    }
```

This is what I would want:
```
  return PopopDialogBuilder(context)
                .setList(images[position])
```

**Comment by smhdk** [comment]
> Let's say that I have a list with 10 images. When I press the fourth image the Popup-Image-Slider starts but with the first image and not with the selected one.
> 
> ```
> private fun showFullscreenImage(images: MutableList<String>): Dialog {
>         return PopopDialogBuilder(context)
>                 .setList(images)
>                 .setHeaderBackgroundColor(R.color.textColorPrimary)
>                 .setDialogBackgroundColor(R.color.color_dialog_bg)
>                 .setCloseDrawable(R.drawable.ic_close_white_24dp)
>                 .setLoadingView(R.layout.loading_view)
>                 .setDialogStyle(R.style.DialogStyle)
>                 .showThumbSlider(false)
>                 .setIsZoomable(true)
>                 .setSelectorIndicator(R.drawable.sample_indicator_selector)
>                 .build()
>     }
> ```
> This is what I would want:
> 
> ```
>   return PopopDialogBuilder(context)
>                 .setList(images[position])
> ```

Hi @AlexandruDev 

Thanks for your review and sorry my to late answer. You can do it using setList method as follows with new version v1.2.1

`.setList(list,position)`
